server:
  port: 80
spring:
  application:
    name: circuit-breaker-app
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        import-check:
          enabled: false
  config:
    import: optional:flowcontrol.yml

---
#spring:
#  cloud:
#    sentinel:
#      degrade:
#        - predicate:
#            - Feign=foo
#          rules:
#            - grade: 2
#              count: 1
#              timeWindow: 10
#              statIntervalMs: 1000
#              minRequestAmount: 1
#        - predicate:
#            - name: RestTemplate
#              args:
#                service: foo
#                path: /**
#          rules:
#            - grade: 2
#              count: 1
#              timeWindow: 10
#              statIntervalMs: 1000
#              minRequestAmount: 1
